#
# Executes commands at the start of an interactive session.

#############################
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#############################
# Customize to your needs...

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh
alias workoff='deactivate'

# alias
alias lla='ls -lA'
alias cls='clear'
alias sshcse='echo "change me alias"; ssh zzzzzzzz@cse.unsw.edu.au'
alias sftpcse='echo "change me alias"; sftp zzzzzzzz@cse.unsw.edu.au'

# better git via https://github.com/github/hub
source /Users/ClemChowder/share/_system/git-flow-completion.zsh
alias git='hub'

# zsh
unsetopt correct
prompt damoekri
unalias rm
export EDITOR=`which vim`

# gnu coreutils (replaces osx BSD builtins. call with 'g' prefix)
unalias ls
alias ls='gls --color --group-directories-first'
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"

# c++ alias
alias gpp='g++ -std=c++14 -Wall -Werror -O2'
